exports.msg = {
    method_not_allowed: 'Method Not Allowed!',
    user_already_exits: "User Already Exists!",
    email_delivery_failed: "Email Delivery Failed!",
    user_created: "User Created Successfully!",
    user_create_failed: "Failed to Create User",
    invalid_token: "Invalid Token!",
    signin_user_not_found: "User Not Found!",
    signup_email_already_verified: "Email Already Verified!",
    signup_email_verification_successful: "Email Verification Successful!",
    email_verification_token_update: "Email Verification Token Updated!",
    email_verification_token_new: "New Email Verification Token Sent!",
    email_verification_sent_user: "Sent Verification Email!",
    resend_email_verification_token_failed: "Failed to Resend Verification Email!",
    signin_invalid_password: "Invalid Password!",
    signin_email_not_verified: "Email Not Verified!",
    signin_success: "Sign In Successful!",
    token_refresh_expired: "Refresh Token Expired!",
    token_refresh_success: "Successfully Created New Refresh Token!",
    missing_token: "Token is Missing!",
    token_valid: "Token is Valid!",
    reset_password_failed: "Failed to Reset the Password!",
    reset_password_email_successful: "Reset password link emailed to user!",
    reset_password_token_time_limit_not_over: "Reset Password token time limit not over!",
    password_update_successful: "Password Updated Successfully!",
    password_update_failed: "Failed to Update Password!",
    bad_request: "Bad Request!",
};